version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment: 
      - POSTGRES_PASSWORD=myDatabasePassword
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5 
  theredshirts-lobby:
    image: "beancodede/theredshirts-lobby:latest"
    container_name: theredshirts-lobby
    restart: always
    environment: 
      - POSTGRES_PASSWORD=myDatabasePassword
      - LOG_LEVEL=debug
    ports:
      - 1203:1203
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres:postgres